Root:
  children:
    Carpals:
      name: Carpals:1
      children:
        Thumb:
          name: T-Assembly:1
          children:
            1: T-AP:1
            2: T-AP_OUT:1
            3: T-AP_IN:1
        Ring:
        Middle:
        Index:
        Pinky:


